options:
  install-type:
    type: string
    default: "Single"
    description: "Type of installation to perform, only supports Single for now."
  openstack-release:
    type: string
    default: "kilo"
    description: "OpenStack release to deploy"
  openstack-password:
    type: string
    default: pass
    description: "Default OpenStack password"
  ubuntu-series:
    type: string
    default: "trusty"
    description: "Ubuntu release to deploy onto"
  upstream-ppa:
    type: boolean
    default: true
    description: "Use experimental PPA"
