options:
  install-type:
    type: string
    default: "Single"
    description: "Type of installation to perform, Single, Multi, or OpenStack Autopilot"
  maas-server:
    type: string
    default: "127.0.0.1"
    description: "IP address of MAAS server if multi install"
  maas-apikey:
    type: string
    default: ""
    description: "MAAS API key of user to access nodes if multi install"
  landscape-name:
    type: string
    default: "ubuntu"
    description: "Admin name"
  landscape-email:
    type: string
    default: "root@localhost"
    description: "Admin email"
  openstack-release:
    type: string
    default: "kilo"
    description: "OpenStack release to deploy"
  openstack-password:
    type: string
    default: pass
    description: "Default OpenStack password"
  ubuntu-series:
    type: string
    default: "trusty"
    description: "Ubuntu release to deploy onto"
  upstream-ppa:
    type: bool
    default: true
    description: "Use experimental PPA"