#!/bin/bash -ex

status-set waiting "Waiting for Ubuntu OpenStack Installer to complete"
su ubuntu -c "sudo openstack-install -c $CHARM_DIR/tmp/osi-config.yaml"
status-set active "Ready for test runs"
